### PR TITLE
Update dependency version and docs

### PR DESCRIPTION
**Pull request by conanak99**
1. Update readme.md to include:
   - How to install dependencies
   - Troubleshoot issue `Please check mosaic_position_model_path!`
   - Troubleshoot issue when building `scikit-image`
2. Bump version of numpy to `1.19.3` to solve conflict with opencv_python (openvc_python require numpy >=1.19.3)

### CODE REVIEW

**Comment by duc622** [comment]
á đù vip pro

**Comment by leanhboi1999** [comment]
Chất quá chất

**Comment by quanghuybest2k2** [comment]
được quá idol

**Comment by hieudicodedao** [comment]
pro víp no 1

**Comment by HungTrinh99** [comment]
oke lam idol

**Review by axelnguyen0701 — APPROVED** [review]

**Pull request merged**
